### ISSUE TITLE
How can i Copy/Download results file/logs from the jmeter-master-********?

### ISSUE THREAD

**Issue by tavish9** [petegrimsdale/aks_testing_fwk#8]

**Comment by petegrimsdale** [comment]
is there a reason you need the results given they are all sent to InfluxDB ?

**Comment by tavish9** [comment]
Thanks. 
One more question. I am using various JMeter plugins in my script. Any mechanism to push the plugins when creating framework/pushing JMeter image?

**Comment by petegrimsdale** [comment]
that is something we have been thinking about adding so that the plugins are available on all slaves. You could amend the local Dockerfile in the /slave directory in your local clone to copy the plugins into the slave image - for an example take a look at https://github.com/egaillardon/jmeter-plugins

**Comment by petegrimsdale** [comment]
@tavish9 - latest version currently on branch now includes the ability to update the images being used
